### ISSUE TITLE
chatbox overlapping

### ISSUE THREAD

**Issue by jerrylin1022** [vahidhedayati/grails-wschat-plugin#19]
Hi, I'm a coding rookie, thanks for this plugin, my grails version is 2.4.3, plugin version is 1.2.5.
I want to use the private message function, a man can receive many private message.
But when the man want to reply message, the chatboxes' position are overlapping.
I don't know how to fix it.
![image 2](https://cloud.githubusercontent.com/assets/17740248/13631147/0d801792-e61e-11e5-8570-14df523dfb7b.png)

**Comment by vahidhedayati** [comment]
Grails 2 version of the  code has fallen behind. Will take a lot of work to put it right. As a temporary fix try downloading this file https://raw.githubusercontent.com/vahidhedayati/grails-wschat-plugin/master/grails-app/assets/javascripts/jquery.ui.chatbox.js and putting this inside your assets/javascript or web-app/js folder.

This should override the plugin's version and then work. Let me know if it works or not

**Comment by vahidhedayati** [comment]
Okay I have now brought grails 2 version of the plugin inline with grails 3. [Please try version 
1.29.](https://github.com/vahidhedayati/grails-wschat-plugin/wiki/Installation)

Also Refer to the [testwschat](https://github.com/vahidhedayati/testwschat) plugin [Config.groovy](https://github.com/vahidhedayati/testwschat/blob/master/grails-app/conf/Config.groovy#L227-L264) file since I have introduced spring security in this latest release and I disabled it in the configuration of this test site.

**Comment by jerrylin1022** [comment]
Hi, I try the first method, but the result is the same. I will try version 1.29 and report result for you.

**Comment by jerrylin1022** [comment]
Hi, I have tried version 1.29, in wschat.js. The function sendPM(receiver,sender,pm) line 774 has error.
I corrent it to "verifyPosition(sender);", and it seems ok.
Thanks for your help.
