### ISSUE TITLE
WSCHAT error accessing

### ISSUE THREAD

**Issue by idiengaid** [vahidhedayati/grails-wschat-plugin#26]
Hi,
i've download your testapp for grails 2.4.4 but i don't find the version of wschat so idecided to put wschat1.31 on buildconfig after running it started but when i go to myapp:
http://localhost:8080/testwschat/wsChat i put a name and choose a room
but it open and give me and error immediately:

Error DOH
user1 disconnecting from server DOH
![image](https://cloud.githubusercontent.com/assets/19474979/23058500/313d6750-f4ed-11e6-9221-dc2d3fe6a05a.png)

and there is no log in console.
Any idea ??
Tks
Windows 7
GGts 364
grails 244
jdk 1.7

**Comment by vahidhedayati** [comment]
The problem appears to be that on that specific site I must have been fiddling with wss

if you open up developer console you will see the problem:

chat:610 WebSocket connection to 'wss://localhost:8443/testwschat/WsChatEndpoint/fred' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
wschat.js?compile=false:832 WebSocket is already in CLOSING or CLOSED state.
wschat.js?compile=false:833 WebSocket is already in CLOSING or CLOSED state.

In the config change:

```
wschat.hostname='localhost:8443'
wschat.wsProtocol='wss'
wschat.siteProtocol='https'
﻿```
to

```
wschat.hostname='localhost:8080'
wschat.wsProtocol='ws'
wschat.siteProtocol='http'
```
​take a look here the demo site has also now been updated to work from now on

https://github.com/vahidhedayati/testwschat/commit/be03f4314b2b1619ebbf3c2db8ae75844563a63e

**Comment by idiengaid** [comment]
ok let me try
tks

**Comment by idiengaid** [comment]
so it's working but with 8081 on the port .
i don't know why but 8080 don't start
thanks now i'll try to understand how it work
if u have any user guide (LOL) i will like use it
tks again

**Comment by vahidhedayati** [comment]
You must still have something running on port 8080 - from msdos prompt  

try `netstat -plant `  then trace kill the java process alternatively look in you windows processes running and kill off all java processes start again to run on port 8080.

so far as documentation take a look through the various links provided and the wiki pages that are part of the links.

Sorry it is in bits and not a full documentation guide due to development over different stages of the plugin 

Feel free to contribute happy to add you along if you want to improve documentation

**Comment by idiengaid** [comment]
it's fine for me i'll be very proud to contribute in documentation 
i'll try to improve this tool really amazing believe me.
Congratulation

**Comment by vahidhedayati** [comment]
:) thank you for the compliment, in all honesty this was a plugin based on me also learning websockets, started from a very basic java application example and grew over time.

So far as understanding all of it, it is difficult since it tries to cover a lot of different things as part of a chat room system i.e. live chat, room booking conferencing. application events and also things like the addons such as tictactoe.

it all depends on what you are trying to learn out of it yourself for you to wish to understand that segment.
Feel free to browse through all the closed topics https://github.com/vahidhedayati/grails-wschat-plugin/issues?q=is%3Aissue+is%3Aclosed  which gives you insight into some of the additions / ideas and probably a little look in the code too.

The videos will also help, if you wish to understand something better and so long as i don't have to pull apart code to explain then email me direct i think my email address was sent as part of this communication

**Comment by idiengaid** [comment]
Ok fine i'll look for i'm a big user of videoconference tools and elearning like bigbluebutton, moodle cisco webex, dimdim,... 
Usually i integrated these tools in my existing developpement cuz i never try to develop something like that. 
But i'll try to follow doc after testing mailling list i've seen today also interesting.
By the way i cannot acces to your mail it's notification@github.com who send me take mine idrissa.engaid@gmail.com

**Comment by vahidhedayati** [comment]
Was going to email you but then thought as it is here it may help others 

In short if you reverse the BuildConfig to use wschat as the inline plugin as in the very last commented out line in buildConfig 

then clone this plugin
`git clone -b grails2 http://github.com/vahidhedayati/grails-wschat-plugin`

outside of the `testwschat` folder it then becomes accessible in development mode 
[you can then look at this specific segment](https://github.com/vahidhedayati/grails-wschat-plugin/blob/master/grails-app/controllers/grails/plugin/wschat/WsChatController.groovy#L251-L258)
and add custom println and output what is going on - also then add println to the socket end point file and figure out how messages are coming in.

Unsure what your scope / level is and what your goal is - if you wish to understand how that part of it as in conferencing works above is a good starting point,

Reason behind the feature was in my previous work place they were paying lots of money to third party companies to have something similar - obviously better. It never took off hence it probably is in the state it is in - working but not perfect or excelling
