### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by grandec** [vahidhedayati/grails-wschat-plugin#3]
Hi,
I use this plugin and the "Concurrent Modification Exception" is thrown when i create a Session, disconnect, and create it again. The exception happens in the "sendUserList" method, i think it happens because when it is iterating to send all the user that a user has disconnected, someone enters the room and the map is updated with the new user while it is iterating. Even if the Set is set as synchronized, the iterator is not, so the problem happens.

**Comment by vahidhedayati** [comment]
" wschat does not accept user with the same name, even at different rooms."

This should now work - as in one user should be able to log in multiple times to different rooms (not the same one)

```groovy
	compile ":wschat:1.13-SNAPSHOT" 
```

problem was with : https://github.com/vahidhedayati/grails-wschat-plugin/blob/master/grails-app/services/grails/plugin/wschat/auth/WsChatAuthService.groovy#L28

**Comment by grandec** [comment]
Hi, happy new year. :D

With this new version, when I log in to different rooms with the same log in, how the messaging will works? The messages goes to the last room logged?

**Comment by vahidhedayati** [comment]
Nope the user in effect logs in to two different rooms and sends messages to each room.

I have not delved into PM's maybe I need to test this now.

BTW  I logged to warn that from 1.11 to 1.13 lots of DB changes so it may break - may be worth backing up previous db and you may need to remove the tables and let it recreate--

On the side note - you can also enable Offline PM's. in short in a scenario server (master) goes offline messages should pop up - upon reconnection

**Comment by vahidhedayati** [comment]
Nope the user in effect logs in to two different rooms and sends messages to each room.

I tested this using a normal chat then invited myself to a conference which was a different room convention

[ChatRoomList.groovy#L7(]https://github.com/vahidhedayati/grails-wschat-plugin/blob/master/grails-app/domain/grails/plugin/wschat/ChatRoomList.groovy#L7) I have now added roomTypes for [Booking-chat-event](https://github.com/vahidhedayati/grails-wschat-plugin/wiki/Booking-chat-event)

Hmmm so here is the run down after a test - very buggy pms going to wrong windows. Users list overwritten . But I think this is due to some of these refreshes going on - 

If you want I can work with this tomorrow and see if there is a way of localising PM's more based to user iterator in the room - disable sending out room info on any rooms that are not of roomType chat which would then mean setting up rooms that have other types for this type of work,



On the side note - you can also enable Offline PM's. in short in a scenario server (master) goes offline messages should pop up - upon reconnection

**Comment by vahidhedayati** [comment]
Okay more thoughts.

If you can work with creating variations of room types.

So user called server joins room called room1 of room type ab

Then server joins rooms room2 of room type xyz

If you can work with that sort  of model I could work on a room iterator.
Adding room types  as they arrive with a user joining.
Then set user iteration to be roomtype_username set a new session value for
real username then call this for display. Additional  session  field
holding user room type.

Finally a delve into messaging to find roomtype_username

This would allow 1 user to get messages uniquely

If you can work on roomtype variations I can look  into rest.

Let me know

**Comment by grandec** [comment]
Hi,
In the application that I am working, the rooms might have 5000 users connected at the same time in the same room, and every time that a user joins or leaves, the plugin sends to every user the updated list of the current online users. Can you put a variable to disable this? I'm starting to worry that a lot of time and data is going to be wasted sending all the users the userlist every time.
Thanks a lot :D 
see ya.

**Comment by vahidhedayati** [comment]
Hi hope all is well, :)

I have released 1.13-SNAPSHOT2 with this enable:

wschat.send.userList='no'

Which should stop sending the users list, yes the room iterator is something I had been thinking about the complications of all of this would be now that I have a friends list that also looks up users globally etc.. I have reverted that other change back (allowing user to login twice) since it was not working as it should have been.

I will look into it again soon

**Comment by grandec** [comment]
Thank you :D

**Comment by grandec** [comment]
Thank you :D

**Comment by vahidhedayati** [comment]
cool :) I guess its working

**Comment by vahidhedayati** [comment]
Hi Victor, hope all is well. Finally moved over the user list to concurrent hash map. Hopefully it will fix those issues from early on this year.

**Comment by vahidhedayati** [comment]
https://github.com/vahidhedayati/grails-wschat-plugin/issues/7 nudge nudge wink wink got that multiple log in working in the end. Failed that first time a very long time ago and I kind of gave up back then.. Anyways dual log in now works too. 

Will close this issue - open a new one if required
